# Generated by Django 4.1.7 on 2023-05-09 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('Documentacion', models.CharField(choices=[('Nº S.S.', 'Nº Seguridad Social'), ('NIF/NIE', 'NIF/NIE')], default='Nº S.S.', max_length=25)),
                ('NumId', models.CharField(help_text='Nº de afiliación a la Seguridad Social o cualquier otra mutualidad reconocida por el estado. En caso de no disponer de ello se registrará el NIF o NIE', max_length=20, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=25)),
                ('Apellidos', models.CharField(max_length=40)),
                ('Sexo', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre'), ('NS/NR', 'Otro')], default='NIF/NIE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edad', models.CharField(max_length=3)),
                ('Fecha_ingreso', models.DateTimeField()),
                ('Fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('Descripcion', models.CharField(blank=True, max_length=2000, null=True)),
                ('Paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestHospital.paciente')),
            ],
        ),
    ]
