# Generated by Django 4.2.1 on 2023-05-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestHospital', '0002_alter_ingreso_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('NumColegiado', models.CharField(help_text='Número de colegiado', max_length=20, primary_key=True, serialize=False)),
                ('Especialidad', models.CharField(choices=[('trauma', 'traumatología'), ('cirugia', 'cirugía'), ('cardiologia', 'cardiología'), ('neorulogia', 'neurología'), ('urologia', 'urología'), ('oftalmologia', 'oftalmología')], max_length=15)),
                ('Ingresos', models.ManyToManyField(to='gestHospital.ingreso')),
            ],
        ),
    ]
