# Generated by Django 4.2.1 on 2023-05-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestHospital', '0003_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='Especialidad',
            field=models.CharField(choices=[('trauma', 'Traumatología'), ('cirugia', 'Cirugía'), ('cardiologia', 'Cardiología'), ('neorulogia', 'Neurología'), ('urologia', 'Urología'), ('oftalmologia', 'Oftalmología')], max_length=15),
        ),
    ]
