# Generated by Django 5.1.2 on 2024-10-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestHospital', '0004_alter_medico_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Lesion',
            field=models.CharField(blank=True, choices=[('hombro', 'Hombro'), ('codo', 'Codo'), ('muñeca', 'Muñeca'), ('mano', 'Mano'), ('cadera', 'Cadera'), ('rodilla', 'Rodilla'), ('tobillo', 'Tobillo'), ('pie', 'Pie'), ('columna_cervical', 'Columna Cervical'), ('columna_dorsal', 'Columna Dorsal'), ('columna_lumbar', 'Columna Lumbar'), ('cuadriceps', 'Cuádriceps'), ('isquiotibiales', 'Isquiotibiales'), ('gemelos', 'Gemelos'), ('pectoral', 'Pectoral'), ('dorsal', 'Dorsal'), ('trapecio', 'Trapecio'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('gluteos', 'Glúteos'), ('abdomen', 'Abdomen')], max_length=255),
        ),
    ]
