# Generated by Django 5.1.3 on 2024-11-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestHospital', '0006_alter_medico_especialidad_alter_medico_numcolegiado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Lesion',
        ),
        migrations.AlterField(
            model_name='medico',
            name='Especialidad',
            field=models.CharField(choices=[('trauma', 'Traumatology'), ('surgery', 'Surgery'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('urology', 'Urology'), ('ophthalmology', 'Ophthalmology')], max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Documentacion',
            field=models.CharField(choices=[('SSN', 'Social Security Number'), ('NIF/NIE', 'NIF/NIE')], default='SSN', max_length=25),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='NumId',
            field=models.CharField(help_text='Social Security Number or any other mutuality recognized by the state. If unavailable, register NIF or NIE.', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Lesiones',
            field=models.ManyToManyField(blank=True, to='gestHospital.lesion'),
        ),
    ]
